#!/bin/sh
#
# Jenkins uses this script to set up the ant build.  Jenkins will then call
# ant itself once this script has completed.

set -e
set -x

# reset version code/name to current date
versionCodeDate=`date +%s`
versionNameDate=`date +%Y-%m-%d_%H.%M.%S`

sed -i \
    -e "s,android:versionCode=\"[0-9][0-9]*\",android:versionCode=\"$versionCodeDate\"," \
    -e "s,android:versionName=\"\([^\"][^\"]*\)\",android:versionName=\"\1.$versionNameDate\"," \
    AndroidManifest.xml

. ~/.android/bashrc
./ant-prepare.sh
