package org.fdroid.ui

import android.os.Build.VERSION.SDK_INT
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import org.fdroid.fdroid.ui.theme.backgroundLight
import org.fdroid.fdroid.ui.theme.errorContainerDark
import org.fdroid.fdroid.ui.theme.errorContainerLight
import org.fdroid.fdroid.ui.theme.errorDark
import org.fdroid.fdroid.ui.theme.errorLight
import org.fdroid.fdroid.ui.theme.inverseOnSurfaceDark
import org.fdroid.fdroid.ui.theme.inverseOnSurfaceLight
import org.fdroid.fdroid.ui.theme.inversePrimaryDark
import org.fdroid.fdroid.ui.theme.inversePrimaryLight
import org.fdroid.fdroid.ui.theme.inverseSurfaceDark
import org.fdroid.fdroid.ui.theme.inverseSurfaceLight
import org.fdroid.fdroid.ui.theme.onBackgroundDark
import org.fdroid.fdroid.ui.theme.onBackgroundLight
import org.fdroid.fdroid.ui.theme.onErrorContainerDark
import org.fdroid.fdroid.ui.theme.onErrorContainerLight
import org.fdroid.fdroid.ui.theme.onErrorDark
import org.fdroid.fdroid.ui.theme.onErrorLight
import org.fdroid.fdroid.ui.theme.onPrimaryContainerDark
import org.fdroid.fdroid.ui.theme.onPrimaryContainerLight
import org.fdroid.fdroid.ui.theme.onPrimaryDark
import org.fdroid.fdroid.ui.theme.onPrimaryLight
import org.fdroid.fdroid.ui.theme.onSecondaryContainerDark
import org.fdroid.fdroid.ui.theme.onSecondaryContainerLight
import org.fdroid.fdroid.ui.theme.onSecondaryDark
import org.fdroid.fdroid.ui.theme.onSecondaryLight
import org.fdroid.fdroid.ui.theme.onSurfaceDark
import org.fdroid.fdroid.ui.theme.onSurfaceLight
import org.fdroid.fdroid.ui.theme.onSurfaceVariantDark
import org.fdroid.fdroid.ui.theme.onSurfaceVariantLight
import org.fdroid.fdroid.ui.theme.onTertiaryContainerDark
import org.fdroid.fdroid.ui.theme.onTertiaryContainerLight
import org.fdroid.fdroid.ui.theme.onTertiaryDark
import org.fdroid.fdroid.ui.theme.onTertiaryLight
import org.fdroid.fdroid.ui.theme.outlineDark
import org.fdroid.fdroid.ui.theme.outlineLight
import org.fdroid.fdroid.ui.theme.outlineVariantDark
import org.fdroid.fdroid.ui.theme.outlineVariantLight
import org.fdroid.fdroid.ui.theme.primaryContainerDark
import org.fdroid.fdroid.ui.theme.primaryContainerLight
import org.fdroid.fdroid.ui.theme.primaryDark
import org.fdroid.fdroid.ui.theme.primaryLight
import org.fdroid.fdroid.ui.theme.scrimDark
import org.fdroid.fdroid.ui.theme.scrimLight
import org.fdroid.fdroid.ui.theme.secondaryContainerDark
import org.fdroid.fdroid.ui.theme.secondaryContainerLight
import org.fdroid.fdroid.ui.theme.secondaryDark
import org.fdroid.fdroid.ui.theme.secondaryLight
import org.fdroid.fdroid.ui.theme.surfaceBrightDark
import org.fdroid.fdroid.ui.theme.surfaceBrightLight
import org.fdroid.fdroid.ui.theme.surfaceContainerDark
import org.fdroid.fdroid.ui.theme.surfaceContainerHighDark
import org.fdroid.fdroid.ui.theme.surfaceContainerHighLight
import org.fdroid.fdroid.ui.theme.surfaceContainerHighestDark
import org.fdroid.fdroid.ui.theme.surfaceContainerHighestLight
import org.fdroid.fdroid.ui.theme.surfaceContainerLight
import org.fdroid.fdroid.ui.theme.surfaceContainerLowDark
import org.fdroid.fdroid.ui.theme.surfaceContainerLowLight
import org.fdroid.fdroid.ui.theme.surfaceContainerLowestDark
import org.fdroid.fdroid.ui.theme.surfaceContainerLowestLight
import org.fdroid.fdroid.ui.theme.surfaceDimDark
import org.fdroid.fdroid.ui.theme.surfaceDimLight
import org.fdroid.fdroid.ui.theme.surfaceLight
import org.fdroid.fdroid.ui.theme.surfaceVariantDark
import org.fdroid.fdroid.ui.theme.surfaceVariantLight
import org.fdroid.fdroid.ui.theme.tertiaryContainerDark
import org.fdroid.fdroid.ui.theme.tertiaryContainerLight
import org.fdroid.fdroid.ui.theme.tertiaryDark
import org.fdroid.fdroid.ui.theme.tertiaryLight

// The followings are generated by the Material Theme Builder with modifications
// https://www.figma.com/community/plugin/1034969338659738588
// Unused code are and themes with contrast are removed

private val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = Color.Black, // TODO
    onBackground = onBackgroundDark,
    surface = Color(0xff1e1e1e), // TODO
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

@Composable
fun FDroidContent(
    darkTheme: Boolean = isSystemInDarkTheme(),
    dynamicColors: Boolean = false,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        SDK_INT >= 31 && dynamicColors && darkTheme -> {
            dynamicDarkColorScheme(LocalContext.current)
        }
        SDK_INT >= 31 && dynamicColors && !darkTheme -> {
            dynamicLightColorScheme(LocalContext.current)
        }
        darkTheme -> darkScheme
        else -> lightScheme
    }
    MaterialTheme(
        colorScheme = colorScheme,
    ) {
        Surface(content = content)
    }
}
