package org.fdroid.ui.screenshots

import androidx.core.os.LocaleListCompat
import org.fdroid.LocaleChooser.getBestLocale
import org.fdroid.ui.discover.AppDiscoverItem

fun getNewApps(localeList: LocaleListCompat) =
  listOf(
    AppDiscoverItem(
      packageName = "jp.nonbili.noutube",
      name = mapOf("en-US" to "NouTube").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = true,
      imageModel =
        "https://f-droid.org/repo/jp.nonbili.noutube/en-US/icon_A1nC0BkAzsvNhws7y1thjfhF8LJJReXVUORApHsstDE=.png",
    ),
    AppDiscoverItem(
      packageName = "net.thunderbird.android",
      name =
        mapOf(
            "ar" to "ثَندَربِرْد: حرّر صندوق بريدك",
            "be" to "Thunderbird: Вольная Пошта",
            "bg" to "Thunderbird: Освободете пощата",
            "br" to "Thunderbird: Dieubit hor boest degemer",
            "ca" to "Thunderbird: allibereu la vostra safata d'entrada",
            "co" to "Thunderbird : Messaghjeria libera",
            "cs-CZ" to "Thunderbird: Svobodná pošta",
            "cy" to "Thunderbird: Rhyddhau'r Blwch Derbyn",
            "de-DE" to "Thunderbird: Befreie deinen Posteingang",
            "el-GR" to "Thunderbird: Ελεύθερα email",
            "en-GB" to "Thunderbird: Free Your Inbox",
            "en-US" to "Thunderbird: Free Your Inbox",
            "eo" to "Thunderbird: Libera retpoŝtilo",
            "es-ES" to "Thunderbird; libera tu correo",
            "et" to "Thunderbird: e-post sinu jaoks",
            "eu-ES" to "Androiderako Thunderbird",
            "fa-IR" to "تاندربرد: آزادی صندوق ورودی",
            "fi-FI" to "Thunderbird: Vapauta postilaatikkosi",
            "fr-FR" to "Thunderbird : Courriel libre",
            "fy" to "Thunderbird: Befrij jo Postfek",
            "ga" to "Thunderbird: Saor Do Phost",
            "gd" to "Thunderbird: Saorsa dhan phost agad",
            "hi-IN" to "थंडरबर्ड - इन्बॉक्स मुक्त करें",
            "hr" to "Thunderbird: Oslobodite svoju poštu",
            "hu-HU" to "Thunderbird: Szabad levelezés",
            "id" to "Thunderbird: Kosongkan Kotak Masuk Anda",
            "is-IS" to "Thunderbird: Frjáls póstur",
            "it-IT" to "Thunderbird: libera la tua casella di posta",
            "iw-IL" to "ת'אנדרבירד: שחרר את תיבת הדואר שלך",
            "ja-JP" to "Thunderbird: 受信トレイをもっと自由に",
            "lt" to "Thunderbird: lais. savo gaut.",
            "mnw" to "ဂစေံလလဳ: သၠးကဠာလိက်မၞး",
            "nl-NL" to "Thunderbird: Bevrijd uw e-mail",
            "nn" to "Thunderbird: Frigjer innboksen",
            "no-NO" to "Thunderbird: Frigjør innboksen",
            "pl-PL" to "Thunderbird: Uwolnij pocztę",
            "pt-BR" to "Thunderbird: Liberte seu email",
            "pt-PT" to "Thunderbird: Liberte o seu email",
            "ro" to "Thunderbird: poștă liberă",
            "ru-RU" to "Thunderbird: свободная почта",
            "sk" to "Thunderbird: Slobodná Schránka",
            "sl" to "Thunderbird: sprostite svoj nabiralnik!",
            "sq" to "Thunderbird: Free Your Inbox",
            "sr" to "Thunderbird: Ослободите своје сандуче",
            "sv-SE" to "Thunderbird: Frigör din inkorg",
            "ta-IN" to "இடிபறவை: உங்கள் உள்பெட்டி விடுவி",
            "tr-TR" to "Thunderbird: Özgür E-posta",
            "uk" to "Thunderbird: Вільна е-пошта",
            "vi" to "Thunderbird: Giải phóng hộp thư của bạn",
            "zh-CN" to "Thunderbird：解放收件箱",
            "zh-TW" to "Thunderbird: 釋放你的收件匣",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = true,
      imageModel =
        "https://f-droid.org/repo/net.thunderbird.android/en-US/icon_llBuXRxsJFITCCuDze-ENOPa1J_HFZLudN5K3gU-xiU=.png",
    ),
    AppDiscoverItem(
      packageName = "io.element.android.x",
      name =
        mapOf("en-US" to "Element X - Secure Chat & Call").getBestLocale(localeList)
          ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/io.element.android.x/en-US/icon_YBz4_OnMHd7E2Bd_oEza9ImLSlHTpL_C-ovHcKljeFA=.png",
    ),
    AppDiscoverItem(
      packageName = "org.breezyweather",
      name = mapOf("en-US" to "Breezy Weather").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = true,
      imageModel =
        "https://f-droid.org/repo/org.breezyweather/en-US/icon_e18rWq0tKc__3173BVXmiiasM_F7yrUbs6kh7lQffto=.png",
    ),
    AppDiscoverItem(
      packageName = "helium314.keyboard",
      name =
        mapOf(
            "ar" to "HeliBoard",
            "bg" to "HeliBoard",
            "bn" to "হেলিবোর্ড",
            "ca" to "HeliBoard",
            "cs-CZ" to "HeliBoard",
            "de-DE" to "HeliBoard",
            "en-US" to "HeliBoard",
            "es-ES" to "HeliBoard",
            "et" to "HeliBoard",
            "fi-FI" to "HeliBoard",
            "fr-FR" to "HeliBoard",
            "gl-ES" to "HeliBoard",
            "hu-HU" to "HeliBoard",
            "id" to "HeliBoard",
            "is-IS" to "HeliBoard",
            "it-IT" to "HeliBoard",
            "iw-IL" to "הליבורד HeliBoard",
            "lv" to "HeliBoard",
            "nl-NL" to "HeliBoard",
            "pa-PK" to "ہیلی‌بورڈ",
            "pl-PL" to "HeliBoard",
            "pt" to "HeliBoard",
            "pt-BR" to "HeliBoard",
            "ru-RU" to "HeliBoard",
            "ta-IN" to "எலிபோர்டு",
            "tr-TR" to "HeliBoard",
            "uk" to "HeliBoard",
            "zh-CN" to "HeliBoard",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = true,
      imageModel =
        "https://f-droid.org/repo/helium314.keyboard/en-US/icon_-nkf9NO4Zp7Y0YX1AOcQdZMf32R_bPt8AZC2Ycn2v1I=.png",
    ),
    AppDiscoverItem(
      packageName = "dev.imranr.obtainium.fdroid",
      name =
        mapOf("de" to "Obtainium", "en-US" to "Obtainium", "ru-RU" to "Obtainium")
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/dev.imranr.obtainium.fdroid/en-US/icon_8o6Dm3kPEr-C-8U1QdRd9B6DrkXPqLJQ7or0KN7ut_4=.png",
    ),
  )

fun getRecentlyUpdatedApps(localeList: LocaleListCompat) =
  listOf(
    AppDiscoverItem(
      packageName = "com.fsck.k9",
      name =
        mapOf(
            "ar" to "K-9 Mail",
            "be" to "Пошта K-9",
            "bg" to "K-9 Поща",
            "ca" to "K-9 Mail",
            "co" to "K-9 Mail",
            "cs-CZ" to "K-9 Mail",
            "cy" to "K-9 Mail",
            "de" to "K-9 Mail",
            "el-GR" to "K-9 Mail",
            "en-GB" to "K-9 Mail",
            "en-US" to "K-9 Mail",
            "eo" to "K-9 Retpoŝtilo",
            "es" to "K-9 Mail",
            "et" to "K-9 Mail",
            "eu-ES" to "K-9 Mail",
            "fa-IR" to "نامهٔ کی۹",
            "fr" to "Courriel K-9 Mail",
            "fy" to "K-9 Mail",
            "ga" to "K-9 Mail",
            "gd" to "Post K-9",
            "he" to "K-9 דוא\"ל",
            "hi-IN" to "K-9 Mail",
            "hr" to "K-9 Mail",
            "hu-HU" to "K-9 Mail",
            "id" to "Surel K-9",
            "is-IS" to "K-9 - Póstur",
            "it" to "K-9 Mail",
            "ja" to "K-9 Mail",
            "kk" to "K-9 Пошта",
            "ko-KR" to "K-9 메일",
            "lt" to "K-9 paštas",
            "mnw" to "တိုက်လိက် K-၉",
            "nb" to "K-9 E-post",
            "nl-NL" to "K-9 Mail",
            "nn" to "K-9 Mail",
            "pl" to "K-9 Mail",
            "pt-BR" to "K-9 Mail",
            "pt-PT" to "K-9 Mail",
            "ro" to "K-9 Mail",
            "ru" to "Почта K-9",
            "sk" to "K-9 Mail",
            "sl" to "Pošta K-9",
            "sq" to "K-9 Mail",
            "sr" to "K-9 Mail",
            "sv-SE" to "K-9 Mail",
            "ta-IN" to "கே-9 அஞ்சல்",
            "tr" to "K-9 Posta",
            "uk" to "K-9 Mail",
            "vi" to "K-9 Mail",
            "zh-CN" to "K-9 Mail",
            "zh-TW" to "K-9 Mail",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.fsck.k9/en-US/icon_-2bZW0ZnkKqPVher2SxQK8hXGGSjgaBHoa8x6vW0v8w=.png",
    ),
    AppDiscoverItem(
      packageName = "com.github.andreyasadchy.xtra",
      name = mapOf("en-US" to "Xtra").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.github.andreyasadchy.xtra/en-US/icon_yfnxF0cNrXwFX2a93BUclISVaIQzoRmbOuxtGDAwz28=.png",
    ),
    AppDiscoverItem(
      packageName = "com.github.libretube",
      name = mapOf("en-US" to "LibreTube").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.github.libretube/en-US/icon_p6_cfoYk-2IlerJpH4rKIQmkI76zXtS3R9-RZp-3Ggk=.png",
    ),
    AppDiscoverItem(
      packageName = "com.inspiredandroid.linuxcommandbibliotheca",
      name = mapOf("en-US" to "Linux Command Library").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.inspiredandroid.linuxcommandbibliotheca/en-US/icon_DrA_e_52nvGa_kTMSapBw4MCqKpccl8WZqrG5enB7rI=.png",
    ),
    AppDiscoverItem(
      packageName = "com.junkfood.seal",
      name =
        mapOf(
            "ar-SA" to "Seal",
            "bn" to "সিল",
            "de-DE" to "Seal",
            "en-US" to "Seal",
            "es" to "Seal",
            "fr-FR" to "Seal",
            "hi" to "सील",
            "hr" to "Seal",
            "id" to "Seal",
            "it" to "Seal",
            "ja" to "Seal",
            "ml" to "സീൽ",
            "nb-NO" to "Seal",
            "nl-NL" to "Zeehond",
            "pt-BR" to "Seal",
            "ru" to "Seal",
            "th" to "Seal",
            "uk" to "Тюлень",
            "vi" to "Hải Cẩu",
            "zh-CN" to "Seal",
            "zh-TW" to "Seal",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.junkfood.seal/en-US/icon_j8mCLA_OX-sJn7TRAdvoaUMW1f6djRv6RMzAnNdaG4I=.png",
    ),
    AppDiscoverItem(
      packageName = "com.kunzisoft.keepass.libre",
      name =
        mapOf(
            "ar" to "KeePassDX Passkey Vault",
            "cs-CZ" to "Trezor pro klíče KeePassDX",
            "de-DE" to "KeePassDX Passkey-Tresor",
            "en-US" to "KeePassDX Passkey Vault",
            "es-ES" to "KeePassDX Passkey Vault",
            "et" to "KeePassDX salasõnahoidla",
            "fr-FR" to "KeePassDX - Passkey local",
            "hr" to "KeePassDX Passkey Vault",
            "hu-HU" to "KeePassDX jelszótároló",
            "id" to "KeePassDX Passkey Vault",
            "it-IT" to "Cassaforte passkey KeePassDX",
            "ja-JP" to "KeePassDX パスワード管理ツール",
            "lt" to "KeePassDX slaptažodžių seifas",
            "lv" to "KeePassDX: paroļu pārvaldnieks",
            "mk-MK" to "KeePassDX Passkey Vault",
            "nl-NL" to "KeePassDX Passkey-kluis",
            "pl-PL" to "KeePassDX – Bezpieczny sejf",
            "ru-RU" to "KeePassDX - менеджер паролей",
            "sq" to "Kasafortë Kyçklm. KeePassDX",
            "th" to "ตู้นิรภัยพาสคีย์คียพาสดีเอ็กซ์",
            "tr-TR" to "KeePassDX Passkey Vault",
            "zh-CN" to "KeePassDX 密码库",
            "zh-TW" to "KeePassDX 密碼（金鑰/單字）保險庫",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.kunzisoft.keepass.libre/en-US/icon_eLwXEQD9l2URrUS3t8esDXnsKGBaH02E-ddEYhV_i7Q=.png",
    ),
  )

fun getMostDownloadedApps(localeList: LocaleListCompat) =
  listOf(
    AppDiscoverItem(
      packageName = "app.organicmaps",
      name =
        mapOf(
            "vi" to "Organic Maps: bản đồ dẫn đường",
            "km-KH" to "Organic Maps・ផែនទីក្រៅបណ្ដាញ",
            "pt-PT" to "Organic Maps - Mapas offline",
            "zh-CN" to "Organic Maps・离线地图与导航 & GPS",
            "iw-IL" to "Organic Maps・מפת אופליין ו-GPS",
            "lv" to "Organic Maps・Kartes・Navigācija",
            "kk" to "Organic Maps: Карталар",
            "hr" to "Organic Maps: offline karte",
            "th" to "Organic Maps: แผนที่gps",
            "si-LK" to "Organic Maps・ඔෆ්ලයින් සිතියම්",
            "sl" to "Organic Maps・Offline Karte",
            "ru-RU" to "Organic Maps: GPS карты офлайн",
            "ne-NP" to "Organic Map・अफलाइन नक्सा & GPS",
            "fr-FR" to "Organic Maps: gps hors ligne",
            "es-ES" to "Organic Maps: mapas offline",
            "mk-MK" to "Organic Maps・Мапи и навигација",
            "be" to "Organic Maps: GPS карты офлайн",
            "lt" to "Organic Maps・žemėlapis & GPS",
            "ms" to "Organic Maps: Peta & Navigasi",
            "en-US" to "Organic Maps・Offline Map & GPS",
            "tr-TR" to "Organic Maps: Haritalar ve GPS",
            "ro" to "Organic Maps: hărți offline",
            "hi-IN" to "Organic Maps・ऑफ़लाइन मैप",
            "mr-IN" to "Organic Maps ऑफलाईन नकाशे",
            "bn-BD" to "Organic Maps・मैप्स और नेविगेशन",
            "ca" to "Organic Map・Mapa Offline i GPS",
            "it-IT" to "Organic Maps: Mappe Offline",
            "uk" to "Organic Maps: GPS карти офлайн",
            "zh-TW" to "Organic Maps・離線地圖與導航 GPS",
            "zh-HK" to "Organic Maps: 地圖與導航",
            "gl-ES" to "Organic Maps・Mapa fóra de liña",
            "bg" to "Organic Maps: офлайн GPS карти",
            "cs-CZ" to "Organic Maps・mapy offline, GPS",
            "ml-IN" to "Organic Maps・ഓഫ്‌ലൈൻ മാപ്പ്",
            "nl-NL" to "Organic Maps: offline kaarten",
            "de-DE" to "Organic Maps Offline Karten",
            "ja-JP" to "Organic Maps: マップ & ナビゲーション",
            "da-DK" to "Organic Maps: Offline Kort",
            "fa" to "Organic Maps・نقشه آفلاین و GPS",
            "ur" to "Organic Maps・Offline Map & GPS",
            "ko-KR" to "Organic Maps・GPS 지도 길찾기 앱 & 地图",
            "id" to "Organic Maps: pemetaan offline",
            "sr" to "Organic Maps・Mape i navigacija",
            "el-GR" to "Organic Maps: Χάρτες & GPS",
            "eu-ES" to "Organic Maps・Offline Map & GPS",
            "hu-HU" to "Organic Maps offline navigáció",
            "lo-LA" to "Organic Maps・ແຜນທີ່ອອບໄລນ໌",
            "no-NO" to "Organic Maps・kart & navigasjon",
            "sv-SE" to "Organic Maps: kartor & GPS",
            "et" to "Organic Maps: gps offline",
            "pl-PL" to "Organic Map・mapy i GPS offline",
            "kn-IN" to "Organic Maps・ಆಫ್‌ಲೈನ್ ಮ್ಯಾಪ್",
            "pt-BR" to "Organic Maps - Mapas offline",
            "ar" to "Organic Maps・خرائط بدون إنترنت",
            "ka-GE" to "Organic Map: ნავიგაცია, რუკები",
            "sk" to "Organic Map・Offline Mapy & GPS",
            "gu" to "Organic Maps・ઓફલાઇન નકશો",
            "az-AZ" to "Organic Maps – Xəritə və GPS",
            "fi-FI" to "Organic Maps: offline kartat",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/app.organicmaps/en-US/icon_dE7f4P95-uKZwu7cI89Q0xSi_-gvU4DD-XnLoDG9RLg=.png",
    ),
    AppDiscoverItem(
      packageName = "at.bitfire.davdroid",
      name = mapOf("ca" to "DAVx⁵", "en-US" to "DAVx⁵").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/at.bitfire.davdroid/en-US/icon_NexNou7vmaD45rbdc8kjLj0Rv7FW128Mde9OQpHFXPE=.png",
    ),
    AppDiscoverItem(
      packageName = "ch.protonvpn.android",
      name =
        mapOf("en-US" to "ProtonVPN - Secure and Free VPN").getBestLocale(localeList)
          ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/ch.protonvpn.android/en-US/icon_xAphlcwMgx7oE7sxB15sxUFIO8geUokWkG01K1fubas=.png",
    ),
    AppDiscoverItem(
      packageName = "com.aurora.store",
      name = mapOf("en-US" to "Aurora Store").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.aurora.store/en-US/icon_tbAhwq51NNd0liZcTg0cQNNvazxrWlj7bPCe_1TkCV8=.png",
    ),
    AppDiscoverItem(
      packageName = "com.duckduckgo.mobile.android",
      name =
        mapOf("en-US" to "DuckDuckGo Privacy Browser").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.duckduckgo.mobile.android/en-US/icon_QyKhnj_C0Pek3xtJAfPFTvywRXDutsVh7r-9t-doP9E=.png",
    ),
    AppDiscoverItem(
      packageName = "com.foobnix.pro.pdf.reader",
      name = mapOf("en-US" to "Librera Reader").getBestLocale(localeList) ?: "Unknown App",
      isInstalled = false,
      imageModel =
        "https://f-droid.org/repo/com.foobnix.pro.pdf.reader/en-US/icon_y15Jxhzp6YrmjLC-wtc27B6XLTcArf7yK-2WlpNaoe0=.png",
    ),
  )
