package org.fdroid.ui.screenshots

import androidx.core.os.LocaleListCompat
import org.fdroid.LocaleChooser.getBestLocale
import org.fdroid.ui.apps.AppUpdateItem
import org.fdroid.ui.apps.InstalledAppItem
import org.fdroid.ui.utils.getPreviewVersion

fun getUpdates(localeList: LocaleListCompat) =
  listOf(
    AppUpdateItem(
      repoId = 1L,
      packageName = "app.comaps.fdroid",
      name =
        mapOf(
            "pt-PT" to "CoMaps - Mapas e Navegação - Offline e Privada",
            "zh-CN" to "CoMaps — 隐私保护下的离线远足、骑行、驾驶",
            "lv" to "CoMaps - dodies ceļā bezsaistē ar privātumu",
            "hr" to "CoMaps - Pješačite, biciklirajte, vozite Offline i",
            "sl" to "CoMaps – potujte brez povezave, zasebno",
            "ru-RU" to "CoMaps - Карты и путешествия с приватностью",
            "fr-FR" to "CoMaps - Randonnée, Vélo, Conduite hors ligne",
            "es-ES" to "CoMaps - Senderismo, ciclismo y conducción offline",
            "lt" to "CoMaps – keliaukite atsijungę ir privačiai",
            "en-US" to "CoMaps - Hike, Bike, Drive Offline with Privacy",
            "tr-TR" to "CoMaps - Gizlilikle Yürüyün, Sürün, Gezin",
            "ro" to "CoMaps - călătorește offline cu confidențialitate",
            "bn-BD" to "কোম্যাপস - অফলাইনে হাইকিং, সাইকেলিং ও ড্রাইভিং",
            "ca" to "CoMaps - Camina, pedala o condueix privadament",
            "it-IT" to "CoMaps - Navigazione Offline con Privacy",
            "uk" to "CoMaps — ходьба та поїздки офлайн із приватність",
            "zh-TW" to "CoMaps — 隱私保護下的離線遠足、騎行、駕駛",
            "gl-ES" to "CoMaps - Aplicación de mapas privada, sen conexión",
            "bg" to "CoMaps - Хайкинг, Велосипед, Пътуване без Интернет",
            "cs-CZ" to "CoMaps – pěšky, na kole a autem offline a soukromě",
            "nl-NL" to "CoMaps - Wandel, fiets, rijd offline met privacy",
            "de-DE" to "CoMaps – Offline navigieren mit Datenschutz",
            "da-DK" to "CoMaps - vandr, cykl og kør offline med privatliv",
            "id" to "CoMaps- Navigasi Offline dengan Privasi",
            "sr" to "CoMaps - пешачење, бицикл и вожња, са приватношћу",
            "el-GR" to "CoMaps - Πλοήγηση εκτός σύνδεσης με ιδιωτικότητα",
            "eu-ES" to "CoMaps - mapak offline eta dena pribatuan",
            "hu-HU" to "CoMaps – túrázás, kerékpározás, autózás offline",
            "no-NO" to "CoMaps -  Gå, Sykle, Kjør Uten Internett",
            "sv-SE" to "Comaps- Vandra, Cykla, Kör Offline, Privat",
            "et" to "CoMaps - sinu privaatne kaart",
            "pl-PL" to "CoMaps - Nawiguj offline z zachowaniem prywatności",
            "kn-IN" to "ಸಹ ನಕ್ಷೆಗಳು - ಆಫ್‌ಲೈನ್ ಮತ್ತು ಗೌಪ್ಯತೆಯೊಂದಿಗೆ",
            "pt-BR" to "CoMaps - Mapas e Navegação Offline com Privacidade",
            "ar" to "CoMaps - تنزه وتنقل وقُد دون إنترنت مع الخصوصية",
            "sk" to "CoMaps - kráčaj, bicykluj a jazdi v súkromí",
            "fi-FI" to "CoMaps - Navigoi yksityisesti ilman verkkoyhteyttä",
            "kw" to "CoMaps - Viajya gans Privetter",
            "fa-IR" to "CoMaps - کوه‌نوردی، دوچرخه‌سواری و رانندگی آفلاین",
            "pt" to "CoMaps - Mapas e Navegação - Offline e Privada",
            "ta-IN" to "இணைவரைபடங்கள் - மலையேறு, வண்டி, தனிமையில் இயக்கு",
            "en-GB" to "CoMaps - Hike, Bike, Drive Offline with Privacy",
            "mt" to "CoMaps - Imxi, Suq Rota u Karozza bil-Privatezza",
            "bn" to "CoMaps - অফলাইনে হাইক, বাইক, ড্রাইভ করুন",
            "brh" to "CoMaps - آفلائن مش لگ، سائکل سواری و موٹر سواری",
            "en-CA" to "CoMaps - Hike, Bike, Drive Offline with Privacy",
            "eo" to "CoMaps - Migru, Biciklu, Veturigu Eksterrete",
            "ast" to "CoMaps - Mapas ensin conexón con privacidá",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2026.05.06-10-FDroid",
      update =
        getPreviewVersion(
          versionName = "2026.05.06-11-FDroid",
          size = 65470491,
        ),
      whatsNew = "foo bar",
      iconModel =
        "https://f-droid.org/repo/app.comaps.fdroid/en-US/icon_Xqa9hlGluoI0ME9XbHrLOaAJ_dX9wWMtDhLgpFYbUOI=.png",
    ),
    AppUpdateItem(
      repoId = 1L,
      packageName = "app.organicmaps",
      name =
        mapOf(
            "vi" to "Organic Maps: bản đồ dẫn đường",
            "km-KH" to "Organic Maps・ផែនទីក្រៅបណ្ដាញ",
            "pt-PT" to "Organic Maps - Mapas offline",
            "zh-CN" to "Organic Maps・离线地图与导航 & GPS",
            "iw-IL" to "Organic Maps・מפת אופליין ו-GPS",
            "ms-MY" to "Organic Maps: Peta & Navigasi",
            "lv" to "Organic Maps・Kartes・Navigācija",
            "am" to "Organic Maps・ከመስመር ውጭ ካርታ & GPS",
            "en-SG" to "Organic Maps・Offline Map & GPS",
            "af" to "Organic Maps・Aflynkaart & GPS",
            "kk" to "Organic Maps: Карталар",
            "hr" to "Organic Maps: offline karte",
            "th" to "Organic Maps: แผนที่gps",
            "si-LK" to "Organic Maps・ඔෆ්ලයින් සිතියම්",
            "sl" to "Organic Maps・Offline Karte",
            "ru-RU" to "Organic Maps: GPS карты офлайн",
            "es-419" to "Organic Maps: mapas sin conexión y GPS",
            "ne-NP" to "Organic Map・अफलाइन नक्सा & GPS",
            "jv" to "Organic Maps・Peta Offline & GPS",
            "fr-FR" to "Organic Maps: gps hors ligne",
            "es-ES" to "Organic Maps: mapas offline",
            "mk-MK" to "Organic Maps・Мапи и навигација",
            "ta-IN" to "Organic Maps・ஆஃப்லைன் வரைபடம்",
            "be" to "Organic Maps: GPS карты офлайн",
            "or" to "Organic Maps・ଅଫଲାଇନ୍ ମ୍ୟାପ୍ ଓ GPS",
            "en-ZA" to "Organic Maps・Offline Map & GPS",
            "fr-CA" to "Organic Maps: gps hors ligne",
            "lt" to "Organic Maps・žemėlapis & GPS",
            "ms" to "Organic Maps: Peta & Navigasi",
            "sq" to "Organic Maps・Hartë Offline & GPS",
            "fa-AE" to "Organic Maps・نقشه آفلاین و GPS",
            "en-US" to "Organic Maps・Offline Map & GPS",
            "bs" to "Organic Maps: Offline mape i GPS",
            "tr-TR" to "Organic Maps: Haritalar ve GPS",
            "ro" to "Organic Maps: hărți offline",
            "en-GB" to "Organic Maps・Offline Map & GPS",
            "ug" to "Organic Maps・تورسىز خەرىتە GPS",
            "hi-IN" to "Organic Maps・ऑफ़लाइन मैप",
            "bo" to "Organic Maps・དྲ་རྒྱ་མེད་ས་ཁྲ། GPS",
            "mr-IN" to "Organic Maps ऑफलाईन नकाशे",
            "bn-BD" to "Organic Maps・मैप्स और नेविगेशन",
            "ca" to "Organic Map・Mapa Offline i GPS",
            "it-IT" to "Organic Maps: Mappe Offline",
            "uk" to "Organic Maps: GPS карти офлайн",
            "fa-AF" to "Organic Maps・نقشه آفلاین و GPS",
            "mn-MN" to "Organic Maps・Офлайн газрын зураг ба GPS",
            "zh-TW" to "Organic Maps・離線地圖與導航 GPS",
            "as" to "Organic Maps・অফলাইন মেপ আৰু GPS",
            "zh-HK" to "Organic Maps: 地圖與導航",
            "gl-ES" to "Organic Maps・Mapa fóra de liña",
            "mi" to "Organic Maps・Mahere Tuimotu GPS",
            "en-AU" to "Organic Maps・Offline Map & GPS",
            "bg" to "Organic Maps: офлайн GPS карти",
            "my-MM" to "Organic Maps・အော့ဖ်လိုင်းမြေပုံနှင့် GPS",
            "cs-CZ" to "Organic Maps・mapy offline, GPS",
            "ml-IN" to "Organic Maps・ഓഫ്‌ലൈൻ മാപ്പ്",
            "nl-NL" to "Organic Maps: offline kaarten",
            "en-CA" to "Organic Maps・Offline Map & GPS",
            "de-DE" to "Organic Maps Offline Karten",
            "zu" to "Organic Maps・Imephu Offline ne-GPS",
            "ja-JP" to "Organic Maps: マップ & ナビゲーション",
            "da-DK" to "Organic Maps: Offline Kort",
            "fa" to "Organic Maps・نقشه آفلاین و GPS",
            "en-IN" to "Organic Maps・Offline Map & GPS",
            "hy-AM" to "Organic Maps・Offline Map & GPS",
            "ur" to "Organic Maps・Offline Map & GPS",
            "mai" to "Organic Maps・ऑफलाइन नक्शा आ GPS",
            "ko-KR" to "Organic Maps・GPS 지도 길찾기 앱 & 地图",
            "id" to "Organic Maps: pemetaan offline",
            "ky-KG" to "Organic Maps・Офлайн карта жана GPS",
            "sr" to "Organic Maps・Mape i navigacija",
            "el-GR" to "Organic Maps: Χάρτες & GPS",
            "eu-ES" to "Organic Maps・Offline Map & GPS",
            "hu-HU" to "Organic Maps offline navigáció",
            "lo-LA" to "Organic Maps・ແຜນທີ່ອອບໄລນ໌",
            "no-NO" to "Organic Maps・kart & navigasjon",
            "rm" to "Organic Maps: Carta Offline & GPS",
            "sw" to "Organic Maps・Ramani Offline na GPS",
            "te-IN" to "Organic Maps・ఆఫ్‌లైన్ మ్యాప్",
            "uz" to "Organic Maps: Oflayn xarita va GPS",
            "sv-SE" to "Organic Maps: kartor & GPS",
            "et" to "Organic Maps: gps offline",
            "pl-PL" to "Organic Map・mapy i GPS offline",
            "kn-IN" to "Organic Maps・ಆಫ್‌ಲೈನ್ ಮ್ಯಾಪ್",
            "fil" to "Organic Maps・Offline na Mapa at GPS",
            "pt-BR" to "Organic Maps - Mapas offline",
            "ar" to "Organic Maps・خرائط بدون إنترنت",
            "ka-GE" to "Organic Map: ნავიგაცია, რუკები",
            "sk" to "Organic Map・Offline Mapy & GPS",
            "pa" to "Organic Maps: ਆਫਲਾਈਨ ਨਕਸ਼ੇ",
            "gu" to "Organic Maps・ઓફલાઇન નકશો",
            "is-IS" to "Organic Maps・Ótengd kort og GPS",
            "az-AZ" to "Organic Maps – Xəritə və GPS",
            "es-US" to "Organic Maps: mapas sin conexión y GPS",
            "fi-FI" to "Organic Maps: offline kartat",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2026.05.27-10-FDroid",
      update =
        getPreviewVersion(
          versionName = "2026.05.27-11-FDroid",
          size = 71778828,
        ),
      whatsNew = "foo bar",
      iconModel =
        "https://f-droid.org/repo/app.organicmaps/en-US/icon_dE7f4P95-uKZwu7cI89Q0xSi_-gvU4DD-XnLoDG9RLg=.png",
    ),
    AppUpdateItem(
      repoId = 1L,
      packageName = "at.bitfire.davdroid",
      name = mapOf("ca" to "DAVx⁵", "en-US" to "DAVx⁵").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.5.12-ose",
      update =
        getPreviewVersion(
          versionName = "4.5.13-ose",
          size = 16018266,
        ),
      whatsNew = null,
      iconModel =
        "https://f-droid.org/repo/at.bitfire.davdroid/en-US/icon_NexNou7vmaD45rbdc8kjLj0Rv7FW128Mde9OQpHFXPE=.png",
    ),
  )

fun getInstalledApps(localeList: LocaleListCompat) =
  listOf(
    InstalledAppItem(
      packageName = "ch.protonvpn.android",
      name =
        mapOf("en-US" to "ProtonVPN - Secure and Free VPN").getBestLocale(localeList)
          ?: "Unknown App",
      installedVersionName = "5.18.75.0",
      installedVersionCode = 1,
      lastUpdated = 1780506857489L,
      iconModel =
        "https://f-droid.org/repo/ch.protonvpn.android/en-US/icon_xAphlcwMgx7oE7sxB15sxUFIO8geUokWkG01K1fubas=.png",
    ),
    InstalledAppItem(
      packageName = "com.aurora.store",
      name = mapOf("en-US" to "Aurora Store").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.8.3",
      installedVersionCode = 1,
      lastUpdated = 1779007734975L,
      iconModel =
        "https://f-droid.org/repo/com.aurora.store/en-US/icon_tbAhwq51NNd0liZcTg0cQNNvazxrWlj7bPCe_1TkCV8=.png",
    ),
    InstalledAppItem(
      packageName = "com.duckduckgo.mobile.android",
      name =
        mapOf("en-US" to "DuckDuckGo Privacy Browser").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "5.281.1",
      installedVersionCode = 1,
      lastUpdated = 1780614376764L,
      iconModel =
        "https://f-droid.org/repo/com.duckduckgo.mobile.android/en-US/icon_QyKhnj_C0Pek3xtJAfPFTvywRXDutsVh7r-9t-doP9E=.png",
    ),
    InstalledAppItem(
      packageName = "com.foobnix.pro.pdf.reader",
      name = mapOf("en-US" to "Librera Reader").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "9.3.75-fdroid",
      installedVersionCode = 1,
      lastUpdated = 1777245514905L,
      iconModel =
        "https://f-droid.org/repo/com.foobnix.pro.pdf.reader/en-US/icon_y15Jxhzp6YrmjLC-wtc27B6XLTcArf7yK-2WlpNaoe0=.png",
    ),
    InstalledAppItem(
      packageName = "com.fsck.k9",
      name =
        mapOf(
            "ar" to "K-9 Mail",
            "be" to "Пошта K-9",
            "bg" to "K-9 Поща",
            "br" to "Postel K-9",
            "ca" to "K-9 Mail",
            "co" to "K-9 Mail",
            "cs-CZ" to "K-9 Mail",
            "cy" to "K-9 Mail",
            "de" to "K-9 Mail",
            "el-GR" to "K-9 Mail",
            "en-GB" to "K-9 Mail",
            "en-US" to "K-9 Mail",
            "eo" to "K-9 Retpoŝtilo",
            "es" to "K-9 Mail",
            "et" to "K-9 Mail",
            "eu-ES" to "K-9 Mail",
            "fa-IR" to "نامهٔ کی۹",
            "fr" to "Courriel K-9 Mail",
            "fy" to "K-9 Mail",
            "ga" to "K-9 Mail",
            "gd" to "Post K-9",
            "gl-ES" to "K-9 Mail",
            "he" to "K-9 דוא\"ל",
            "hi-IN" to "K-9 Mail",
            "hr" to "K-9 Mail",
            "hu-HU" to "K-9 Mail",
            "id" to "Surel K-9",
            "is-IS" to "K-9 - Póstur",
            "it" to "K-9 Mail",
            "ja" to "K-9 Mail",
            "kk" to "K-9 Пошта",
            "ko-KR" to "K-9 메일",
            "lt" to "K-9 paštas",
            "mnw" to "တိုက်လိက် K-၉",
            "nb" to "K-9 E-post",
            "nl-NL" to "K-9 Mail",
            "nn" to "K-9 Mail",
            "pl" to "K-9 Mail",
            "pt-BR" to "K-9 Mail",
            "pt-PT" to "K-9 Mail",
            "ro" to "K-9 Mail",
            "ru" to "Почта K-9",
            "sk" to "K-9 Mail",
            "sl" to "Pošta K-9",
            "sq" to "K-9 Mail",
            "sr" to "K-9 Mail",
            "sv-SE" to "K-9 Mail",
            "ta-IN" to "கே-9 அஞ்சல்",
            "tr" to "K-9 Posta",
            "uk" to "K-9 Mail",
            "vi" to "K-9 Mail",
            "zh-CN" to "K-9 Mail",
            "zh-TW" to "K-9 Mail",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "19.2",
      installedVersionCode = 1,
      lastUpdated = 1780699361309L,
      iconModel =
        "https://f-droid.org/repo/com.fsck.k9/en-US/icon_-2bZW0ZnkKqPVher2SxQK8hXGGSjgaBHoa8x6vW0v8w=.png",
    ),
    InstalledAppItem(
      packageName = "com.github.andreyasadchy.xtra",
      name = mapOf("en-US" to "Xtra").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2.56.2",
      installedVersionCode = 1,
      lastUpdated = 1780506857489L,
      iconModel =
        "https://f-droid.org/repo/com.github.andreyasadchy.xtra/en-US/icon_yfnxF0cNrXwFX2a93BUclISVaIQzoRmbOuxtGDAwz28=.png",
    ),
    InstalledAppItem(
      packageName = "com.github.catfriend1.syncthingfork",
      name =
        mapOf(
            "en-US" to "Syncthing-Fork",
            "vi" to "Syncthing-Fork",
            "he" to "Syncthing-Fork",
            "pt-PT" to "Syncthing-Fork",
            "zh-CN" to "Syncthing-Fork",
            "ru-RU" to "Syncthing-Fork",
            "es-419" to "Syncthing-Fork",
            "fr-FR" to "Syncthing-Fork",
            "es-ES" to "Syncthing-Fork",
            "be" to "Syncthing-Fork",
            "tr-TR" to "Syncthing-Fork",
            "ro" to "Syncthing-Fork",
            "ca" to "Syncthing-Fork",
            "it-IT" to "Syncthing-Fork",
            "uk" to "Syncthing-Fork",
            "zh-TW" to "Syncthing-Fork",
            "bg" to "Syncthing-Fork",
            "cs-CZ" to "Syncthing-Fork",
            "nl-NL" to "Syncthing-Fork",
            "de-DE" to "Syncthing-Fork",
            "ja-JP" to "Syncthing-Fork",
            "da-DK" to "Syncthing-Fork",
            "ko-KR" to "Syncthing-Fork",
            "id" to "Syncthing-Fork",
            "sr" to "Syncthing-Fork",
            "hu-HU" to "Syncthing-Fork",
            "sv-SE" to "Syncthing-Fork",
            "et" to "Syncthing-Fork",
            "pl-PL" to "Syncthing-Fork",
            "pt-BR" to "Syncthing-Fork",
            "ar" to "Syncthing-Fork",
            "sk" to "Syncthing-Fork",
            "es-US" to "Syncthing-Fork",
            "fi-FI" to "Syncthing-Fork",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2.1.0.0",
      installedVersionCode = 1,
      lastUpdated = 1778740722978L,
      iconModel =
        "https://f-droid.org/repo/com.github.catfriend1.syncthingfork/en-US/icon_egWOwTWZpQ_1CxmdrwP5wRta5EVmCCuzQWxjI5JTs0w=.png",
    ),
    InstalledAppItem(
      packageName = "com.github.libretube",
      name = mapOf("en-US" to "LibreTube").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "31.4",
      installedVersionCode = 1,
      lastUpdated = 1780094298321L,
      iconModel =
        "https://f-droid.org/repo/com.github.libretube/en-US/icon_p6_cfoYk-2IlerJpH4rKIQmkI76zXtS3R9-RZp-3Ggk=.png",
    ),
    InstalledAppItem(
      packageName = "com.inspiredandroid.linuxcommandbibliotheca",
      name = mapOf("en-US" to "Linux Command Library").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.0.6",
      installedVersionCode = 1,
      lastUpdated = 1780012218733L,
      iconModel =
        "https://f-droid.org/repo/com.inspiredandroid.linuxcommandbibliotheca/en-US/icon_DrA_e_52nvGa_kTMSapBw4MCqKpccl8WZqrG5enB7rI=.png",
    ),
    InstalledAppItem(
      packageName = "com.junkfood.seal",
      name =
        mapOf(
            "ar-SA" to "Seal",
            "bn" to "সিল",
            "de-DE" to "Seal",
            "en-US" to "Seal",
            "es" to "Seal",
            "fr-FR" to "Seal",
            "hi" to "सील",
            "hr" to "Seal",
            "id" to "Seal",
            "it" to "Seal",
            "ja" to "Seal",
            "ml" to "സീൽ",
            "nb-NO" to "Seal",
            "nl-NL" to "Zeehond",
            "pt-BR" to "Seal",
            "ru" to "Seal",
            "th" to "Seal",
            "uk" to "Тюлень",
            "vi" to "Hải Cẩu",
            "zh-CN" to "Seal",
            "zh-TW" to "Seal",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "1.13.1-(F-Droid)",
      installedVersionCode = 1,
      lastUpdated = 1767740580000L,
      iconModel =
        "https://f-droid.org/repo/com.junkfood.seal/en-US/icon_j8mCLA_OX-sJn7TRAdvoaUMW1f6djRv6RMzAnNdaG4I=.png",
    ),
  )
