package org.fdroid.ui.screenshots

import androidx.core.os.LocaleListCompat
import org.fdroid.LocaleChooser.getBestLocale
import org.fdroid.ui.apps.AppUpdateItem
import org.fdroid.ui.apps.InstalledAppItem
import org.fdroid.ui.utils.getPreviewVersion

fun getUpdates(localeList: LocaleListCompat) =
  listOf(
    AppUpdateItem(
      repoId = 1L,
      packageName = "app.organicmaps",
      name =
        mapOf(
            "vi" to "Organic Maps: bản đồ dẫn đường",
            "km-KH" to "Organic Maps・ផែនទីក្រៅបណ្ដាញ",
            "pt-PT" to "Organic Maps - Mapas offline",
            "zh-CN" to "Organic Maps・离线地图与导航 & GPS",
            "iw-IL" to "Organic Maps・מפת אופליין ו-GPS",
            "lv" to "Organic Maps・Kartes・Navigācija",
            "kk" to "Organic Maps: Карталар",
            "hr" to "Organic Maps: offline karte",
            "th" to "Organic Maps: แผนที่gps",
            "si-LK" to "Organic Maps・ඔෆ්ලයින් සිතියම්",
            "sl" to "Organic Maps・Offline Karte",
            "ru-RU" to "Organic Maps: GPS карты офлайн",
            "ne-NP" to "Organic Map・अफलाइन नक्सा & GPS",
            "fr-FR" to "Organic Maps: gps hors ligne",
            "es-ES" to "Organic Maps: mapas offline",
            "mk-MK" to "Organic Maps・Мапи и навигација",
            "be" to "Organic Maps: GPS карты офлайн",
            "lt" to "Organic Maps・žemėlapis & GPS",
            "ms" to "Organic Maps: Peta & Navigasi",
            "en-US" to "Organic Maps・Offline Map & GPS",
            "tr-TR" to "Organic Maps: Haritalar ve GPS",
            "ro" to "Organic Maps: hărți offline",
            "hi-IN" to "Organic Maps・ऑफ़लाइन मैप",
            "mr-IN" to "Organic Maps ऑफलाईन नकाशे",
            "bn-BD" to "Organic Maps・मैप्स और नेविगेशन",
            "ca" to "Organic Map・Mapa Offline i GPS",
            "it-IT" to "Organic Maps: Mappe Offline",
            "uk" to "Organic Maps: GPS карти офлайн",
            "zh-TW" to "Organic Maps・離線地圖與導航 GPS",
            "zh-HK" to "Organic Maps: 地圖與導航",
            "gl-ES" to "Organic Maps・Mapa fóra de liña",
            "bg" to "Organic Maps: офлайн GPS карти",
            "cs-CZ" to "Organic Maps・mapy offline, GPS",
            "ml-IN" to "Organic Maps・ഓഫ്‌ലൈൻ മാപ്പ്",
            "nl-NL" to "Organic Maps: offline kaarten",
            "de-DE" to "Organic Maps Offline Karten",
            "ja-JP" to "Organic Maps: マップ & ナビゲーション",
            "da-DK" to "Organic Maps: Offline Kort",
            "fa" to "Organic Maps・نقشه آفلاین و GPS",
            "ur" to "Organic Maps・Offline Map & GPS",
            "ko-KR" to "Organic Maps・GPS 지도 길찾기 앱 & 地图",
            "id" to "Organic Maps: pemetaan offline",
            "sr" to "Organic Maps・Mape i navigacija",
            "el-GR" to "Organic Maps: Χάρτες & GPS",
            "eu-ES" to "Organic Maps・Offline Map & GPS",
            "hu-HU" to "Organic Maps offline navigáció",
            "lo-LA" to "Organic Maps・ແຜນທີ່ອອບໄລນ໌",
            "no-NO" to "Organic Maps・kart & navigasjon",
            "sv-SE" to "Organic Maps: kartor & GPS",
            "et" to "Organic Maps: gps offline",
            "pl-PL" to "Organic Map・mapy i GPS offline",
            "kn-IN" to "Organic Maps・ಆಫ್‌ಲೈನ್ ಮ್ಯಾಪ್",
            "pt-BR" to "Organic Maps - Mapas offline",
            "ar" to "Organic Maps・خرائط بدون إنترنت",
            "ka-GE" to "Organic Map: ნავიგაცია, რუკები",
            "sk" to "Organic Map・Offline Mapy & GPS",
            "gu" to "Organic Maps・ઓફલાઇન નકશો",
            "az-AZ" to "Organic Maps – Xəritə və GPS",
            "fi-FI" to "Organic Maps: offline kartat",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2026.02.18-4-FDroid",
      update = getPreviewVersion(versionName = "2026.02.18-5-FDroid", size = 70355961),
      whatsNew = "foo bar",
      iconModel =
        "https://f-droid.org/repo/app.organicmaps/en-US/icon_dE7f4P95-uKZwu7cI89Q0xSi_-gvU4DD-XnLoDG9RLg=.png",
    ),
    AppUpdateItem(
      repoId = 1L,
      packageName = "at.bitfire.davdroid",
      name = mapOf("ca" to "DAVx⁵", "en-US" to "DAVx⁵").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.5.8-ose",
      update = getPreviewVersion(versionName = "4.5.9-ose", size = 15974669),
      whatsNew = null,
      iconModel =
        "https://f-droid.org/repo/at.bitfire.davdroid/en-US/icon_NexNou7vmaD45rbdc8kjLj0Rv7FW128Mde9OQpHFXPE=.png",
    ),
    AppUpdateItem(
      repoId = 1L,
      packageName = "ch.protonvpn.android",
      name =
        mapOf("en-US" to "ProtonVPN - Secure and Free VPN").getBestLocale(localeList)
          ?: "Unknown App",
      installedVersionName = "5.16.30.9",
      update = getPreviewVersion(versionName = "5.16.31.0", size = 54161941),
      whatsNew = "foo bar",
      iconModel =
        "https://f-droid.org/repo/ch.protonvpn.android/en-US/icon_xAphlcwMgx7oE7sxB15sxUFIO8geUokWkG01K1fubas=.png",
    ),
  )

fun getInstalledApps(localeList: LocaleListCompat) =
  listOf(
    InstalledAppItem(
      packageName = "com.aurora.store",
      name = mapOf("en-US" to "Aurora Store").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.8.1",
      installedVersionCode = 1,
      lastUpdated = 1771544205000L,
      iconModel =
        "https://f-droid.org/repo/com.aurora.store/en-US/icon_tbAhwq51NNd0liZcTg0cQNNvazxrWlj7bPCe_1TkCV8=.png",
    ),
    InstalledAppItem(
      packageName = "com.duckduckgo.mobile.android",
      name =
        mapOf("en-US" to "DuckDuckGo Privacy Browser").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "5.268.1",
      installedVersionCode = 1,
      lastUpdated = 1772699310000L,
      iconModel =
        "https://f-droid.org/repo/com.duckduckgo.mobile.android/en-US/icon_QyKhnj_C0Pek3xtJAfPFTvywRXDutsVh7r-9t-doP9E=.png",
    ),
    InstalledAppItem(
      packageName = "com.foobnix.pro.pdf.reader",
      name = mapOf("en-US" to "Librera Reader").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "9.3.63-fdroid",
      installedVersionCode = 1,
      lastUpdated = 1772574994000L,
      iconModel =
        "https://f-droid.org/repo/com.foobnix.pro.pdf.reader/en-US/icon_y15Jxhzp6YrmjLC-wtc27B6XLTcArf7yK-2WlpNaoe0=.png",
    ),
    InstalledAppItem(
      packageName = "com.fsck.k9",
      name =
        mapOf(
            "ar" to "K-9 Mail",
            "be" to "Пошта K-9",
            "bg" to "K-9 Поща",
            "ca" to "K-9 Mail",
            "co" to "K-9 Mail",
            "cs-CZ" to "K-9 Mail",
            "cy" to "K-9 Mail",
            "de" to "K-9 Mail",
            "el-GR" to "K-9 Mail",
            "en-GB" to "K-9 Mail",
            "en-US" to "K-9 Mail",
            "eo" to "K-9 Retpoŝtilo",
            "es" to "K-9 Mail",
            "et" to "K-9 Mail",
            "eu-ES" to "K-9 Mail",
            "fa-IR" to "نامهٔ کی۹",
            "fr" to "Courriel K-9 Mail",
            "fy" to "K-9 Mail",
            "ga" to "K-9 Mail",
            "gd" to "Post K-9",
            "he" to "K-9 דוא\"ל",
            "hi-IN" to "K-9 Mail",
            "hr" to "K-9 Mail",
            "hu-HU" to "K-9 Mail",
            "id" to "Surel K-9",
            "is-IS" to "K-9 - Póstur",
            "it" to "K-9 Mail",
            "ja" to "K-9 Mail",
            "kk" to "K-9 Пошта",
            "ko-KR" to "K-9 메일",
            "lt" to "K-9 paštas",
            "mnw" to "တိုက်လိက် K-၉",
            "nb" to "K-9 E-post",
            "nl-NL" to "K-9 Mail",
            "nn" to "K-9 Mail",
            "pl" to "K-9 Mail",
            "pt-BR" to "K-9 Mail",
            "pt-PT" to "K-9 Mail",
            "ro" to "K-9 Mail",
            "ru" to "Почта K-9",
            "sk" to "K-9 Mail",
            "sl" to "Pošta K-9",
            "sq" to "K-9 Mail",
            "sr" to "K-9 Mail",
            "sv-SE" to "K-9 Mail",
            "ta-IN" to "கே-9 அஞ்சல்",
            "tr" to "K-9 Posta",
            "uk" to "K-9 Mail",
            "vi" to "K-9 Mail",
            "zh-CN" to "K-9 Mail",
            "zh-TW" to "K-9 Mail",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "16.1",
      installedVersionCode = 1,
      lastUpdated = 1770745842000L,
      iconModel =
        "https://f-droid.org/repo/com.fsck.k9/en-US/icon_-2bZW0ZnkKqPVher2SxQK8hXGGSjgaBHoa8x6vW0v8w=.png",
    ),
    InstalledAppItem(
      packageName = "com.github.andreyasadchy.xtra",
      name = mapOf("en-US" to "Xtra").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "2.54.3",
      installedVersionCode = 1,
      lastUpdated = 1772397992000L,
      iconModel =
        "https://f-droid.org/repo/com.github.andreyasadchy.xtra/en-US/icon_yfnxF0cNrXwFX2a93BUclISVaIQzoRmbOuxtGDAwz28=.png",
    ),
    InstalledAppItem(
      packageName = "com.github.libretube",
      name = mapOf("en-US" to "LibreTube").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "0.30.0",
      installedVersionCode = 1,
      lastUpdated = 1769702789000L,
      iconModel =
        "https://f-droid.org/repo/com.github.libretube/en-US/icon_p6_cfoYk-2IlerJpH4rKIQmkI76zXtS3R9-RZp-3Ggk=.png",
    ),
    InstalledAppItem(
      packageName = "com.inspiredandroid.linuxcommandbibliotheca",
      name = mapOf("en-US" to "Linux Command Library").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "3.5.13",
      installedVersionCode = 1,
      lastUpdated = 1772463524000L,
      iconModel =
        "https://f-droid.org/repo/com.inspiredandroid.linuxcommandbibliotheca/en-US/icon_DrA_e_52nvGa_kTMSapBw4MCqKpccl8WZqrG5enB7rI=.png",
    ),
    InstalledAppItem(
      packageName = "com.junkfood.seal",
      name =
        mapOf(
            "ar-SA" to "Seal",
            "bn" to "সিল",
            "de-DE" to "Seal",
            "en-US" to "Seal",
            "es" to "Seal",
            "fr-FR" to "Seal",
            "hi" to "सील",
            "hr" to "Seal",
            "id" to "Seal",
            "it" to "Seal",
            "ja" to "Seal",
            "ml" to "സീൽ",
            "nb-NO" to "Seal",
            "nl-NL" to "Zeehond",
            "pt-BR" to "Seal",
            "ru" to "Seal",
            "th" to "Seal",
            "uk" to "Тюлень",
            "vi" to "Hải Cẩu",
            "zh-CN" to "Seal",
            "zh-TW" to "Seal",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "1.13.1-(F-Droid)",
      installedVersionCode = 1,
      lastUpdated = 1767740580000L,
      iconModel =
        "https://f-droid.org/repo/com.junkfood.seal/en-US/icon_j8mCLA_OX-sJn7TRAdvoaUMW1f6djRv6RMzAnNdaG4I=.png",
    ),
    InstalledAppItem(
      packageName = "com.kunzisoft.keepass.libre",
      name =
        mapOf(
            "ar" to "KeePassDX Passkey Vault",
            "cs-CZ" to "Trezor pro klíče KeePassDX",
            "de-DE" to "KeePassDX Passkey-Tresor",
            "en-US" to "KeePassDX Passkey Vault",
            "es-ES" to "KeePassDX Passkey Vault",
            "et" to "KeePassDX salasõnahoidla",
            "fr-FR" to "KeePassDX - Passkey local",
            "hr" to "KeePassDX Passkey Vault",
            "hu-HU" to "KeePassDX jelszótároló",
            "id" to "KeePassDX Passkey Vault",
            "it-IT" to "Cassaforte passkey KeePassDX",
            "ja-JP" to "KeePassDX パスワード管理ツール",
            "lt" to "KeePassDX slaptažodžių seifas",
            "lv" to "KeePassDX: paroļu pārvaldnieks",
            "mk-MK" to "KeePassDX Passkey Vault",
            "nl-NL" to "KeePassDX Passkey-kluis",
            "pl-PL" to "KeePassDX – Bezpieczny sejf",
            "ru-RU" to "KeePassDX - менеджер паролей",
            "sq" to "Kasafortë Kyçklm. KeePassDX",
            "th" to "ตู้นิรภัยพาสคีย์คียพาสดีเอ็กซ์",
            "tr-TR" to "KeePassDX Passkey Vault",
            "zh-CN" to "KeePassDX 密码库",
            "zh-TW" to "KeePassDX 密碼（金鑰/單字）保險庫",
          )
          .getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "4.3.2",
      installedVersionCode = 1,
      lastUpdated = 1768680637000L,
      iconModel =
        "https://f-droid.org/repo/com.kunzisoft.keepass.libre/en-US/icon_eLwXEQD9l2URrUS3t8esDXnsKGBaH02E-ddEYhV_i7Q=.png",
    ),
    InstalledAppItem(
      packageName = "com.looker.droidify",
      name = mapOf("en-US" to "Droid-ify").getBestLocale(localeList) ?: "Unknown App",
      installedVersionName = "0.7.0",
      installedVersionCode = 1,
      lastUpdated = 1771667689000L,
      iconModel =
        "https://f-droid.org/repo/com.looker.droidify/en-US/icon_lApsnfhrMqGkCaW-IdnYwx86CUjdTutncPvXPJythaM=.png",
    ),
  )
